version: '3'
services:
  app:
    container_name: spasial-be #full_app
    build: .
    ports:
      - 8000:8080
    environment:
      - DB_HOST=spasial-postgres
      - DB_USER=postgres
      - DB_PASS=123456789
      - DB_PORT=5432
      - DB_NAME=spasial-2024
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - spasial-postgres #fullstack-mysql
    networks:
      - backend #fullstack


  spasial-postgres: #fullstack-mysql:
    image: postgres:alpine
    container_name: db-postgres #full_db_mysql
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=spasial-2024
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - backend #fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    depends_on:
      - spasial-postgres #fullstack-mysql
    environment:
      PGADMIN_DEFAULT_EMAIL: thoriqagfi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: thoriqagfi
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - backend #fullstack


volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge